### PR TITLE
Map Editor: Complete Step 1

### LINKED ISSUE #2547: Map Editor: Tile Tool Step 1
The Map Editor has a Tile Tool (`client/editor/tool_tile.cpp`), it needs many more capabilities:

- [x] `editor_tool_tile::select_tile()` doesn't do anything. Need to find the proper client or server function to change the mouse cursor to a universal selector so we can select any tile on the map.
- [x] When a tile is selected, populate a `struct tile` with all the properties of the tile
     - [x] Map X Coordinate
     - [x] Map Y Coordinate
     - [x] Native Map X Coordinate
     - [x] Native Map Y Coordinate
     - [x] Continent Number
     - [x] Terrain Type (e.g. Grassland, Jungle) with and icon/pixmap next to the label
     - [x] Resource (if any) with an icon/pixmap next to the label
     - [x] List of Specials - comma separated list for display is probably fine to start with (e.g. irrigation, mine, oil well, oil platform, pollution, hut, farmland, fallout, ruins)
     - [x] List of Roads - comma separated list for display is probably fine to start with
     - [x] List of Bases - comma separated list for display is probably fine to start with
     - [x] Tile Label
     - [x] Tile Visibility
- [x] Populate the labels on the form (not all labels are present at this time)
- [x] Disable universal selection
- [x] If a different tile is selected, then the labels should update

**NOTE**: Notice this task doesn't do anything with a city or units on the tile. That's later.

### LINKED ISSUE #2626: Map Editor segfaults the game when you pick a tile that is not-visible
**Describe the bug**
If you select a tile that is "black" and hasn't been seen by the player in the game, the client crashes

**To Reproduce**
1. ctrl-shift-e to open the editor
2. Click on a black tile
3. See error

**Expected behavior**
no segfault would be nice :)

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.2-dev.0
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
Introduced w/ #2595

### PR DESCRIPTION
**Pull request by jwrober**
This patch completes population all properties of a tile from the editor. This PR also implements two suggestions from #2595 - merge repeated functions into a single one and add help text links for tiles.

Closes #2547 
Closes #2626

### CODE REVIEW

**Comment by jwrober** [comment]
Marking this as a fully ready PR. The last patch fixed my two issues. Turns out I just needed to move the function call for the links down into my new function.

File: client/editor/tool_tile.cpp [hunk 1]
```diff
@@ -133,169 +151,173 @@ void editor_tool_tile::update_ett(struct tile *ptile)
...
+          names.push_back(
+              create_help_link(extra_name_translation(pextra), HELP_EXTRA));
+        }
+      }
+      extra_type_by_cause_iterate_end;
+      break;
+    case EC_APPEARANCE:
+    case EC_COUNT:
+      break;
     }
```
Comment (lmoureaux) [inline client/editor/tool_tile.cpp:315]: I think this should work:
```suggestion
    extra_type_by_cause_iterate(cause, pextra)
    {
      if (tile_has_extra(ptile, pextra)) {
        names.push_back(
            create_help_link(extra_name_translation(pextra), HELP_EXTRA));
      }
    }
    extra_type_by_cause_iterate_end;
```
Not sure what `EC_APPEARANCE` is for, does it hurt to keep it?

File: client/editor/tool_tile.h [hunk 2]
```diff
@@ -3,6 +3,9 @@
 
 #pragma once
 
+// generated
+#include <packets_gen.h>
```
Comment (lmoureaux) [inline client/editor/tool_tile.h:7]: I think this should be `packets.h`...
```suggestion
#include "packets_gen.h"
```

File: client/helpdlg.cpp [hunk 3]
```diff
@@ -112,10 +112,15 @@ QString create_help_link(const char *name, help_page_type hpt)
...
-  QString a = QString::fromUtf8(QString(entry).toUtf8().toPercentEncoding());
-  return "<a href=" + QString::number(hpt) + "," + a + ">" + d + "</a>";
+  if (!QString(name).isEmpty()) {
+    QString d = QString(name).toHtmlEscaped().replace(
+        QStringLiteral(" "), QStringLiteral("&nbsp;"));
+    QString a =
+        QString::fromUtf8(QString(entry).toUtf8().toPercentEncoding());
+    return "<a href=" + QString::number(hpt) + "," + a + ">" + d + "</a>";
+  } else {
+    return nullptr;
```
Comment (lmoureaux) [inline client/helpdlg.cpp:122]: How can the name be empty?
```suggestion
    return QStringLiteral();
```

**Review by lmoureaux — COMMENTED** [review]
I'll want to try it out, but I already have a few code comments

File: client/editor/tool_tile.cpp (hunk 1 above)
Comment (jwrober) [reply client/editor/tool_tile.cpp:315]: Ah ok. I couldn't figure out how to do the full for loop so I did the switch instead.

**Review by blabber — APPROVED** [review]
The tile properties I testes are displayed and linked  correctly, so it seems to work as expected.

The code looks fine too. @lmoureaux  pointed out some issues that have been taken care of. 

LGTM

**Review by lmoureaux — APPROVED** [review]
