### PR TITLE
Restore goto into the unknown

### LINKED ISSUE #890: Restore goto into the unknown
**Describe the bug**

This feature was removed in #824 and does nothing. Restore it (there's an option in the config dialog).

### PR DESCRIPTION
**Pull request by lmoureaux**
Add a flag to the path finder class to control whether it should include
unknown tiles in the search. Bind it to the corresponding gui option when
creating the finders.

This restores the ability to produce paths going through unknown parts of the
map, which is useful in some circumstances.

Closes #890.

### CODE REVIEW

File: common/path_finder.h [hunk 1]
```diff
@@ -110,6 +113,14 @@ class path_finder {
 
   inline path_finder &operator=(path_finder &&other);
 
+  /// Returns whether goto into the unkown is allowed.
+  bool are_unknown_tiles_allowed() const
```
Comment (pranavtifr) [inline common/path_finder.h:117]: Just a small nitpick/comment/suggestion should this be called get_unknown_tiles_allowed() to be consistent with the getter-setter idiom in cpp ? I'm also ok if we consistently name all setters with a question like this. Then it needs to go into coding style and the lot, getter-setter is more standard.

Comment (pranavtifr) [inline common/path_finder.h:117]: Just a small nitpick/comment/suggestion should this be called get_unknown_tiles_allowed() to be consistent with the getter-setter idiom in cpp ? I'm also ok if we consistently name all setters with a question like this. Then it needs to go into coding style and the lot, getter-setter is more standard.

**Comment by pranavtifr** [comment]
Apart from that, looks ok and works ok.

File: common/path_finder.h (hunk 1 above)
Comment (lmoureaux) [reply common/path_finder.h:117]: I'm using the Qt naming convention here: boolean getters start with `is` and others don't have a specific prefix. Someone should push #1179 forward...
