### PR TITLE
Fix units view to show when observing

### LINKED ISSUE #1826: Units view does not do global observing correctly
**Describe the bug**
When global observing with the new units view, the view is empty.

**To Reproduce**
1. Open a local game
2. In chat enter `/observe` to enter global observe
3. Open units view

**Expected behavior**
Similar to the cities and economics view, I would expect to see all units for all nations.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: All supported
 - Freeciv21 version: v3.1-dev (master) at https://github.com/longturn/freeciv21/commit/20ff9bdf0c7441535aec6aa0798cd7f22c77e659
 - Ruleset/Longturn game (if applicable): Any

**Additional context**

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1826

### CODE REVIEW

File: client/views/view_units.cpp [hunk 1]
```diff
@@ -531,61 +531,65 @@ void get_units_view_data(struct unit_view_entry *entries,
...
-    int in_progress = 0;     // Count of being produced
-    int gold_cost = 0;       // Gold upkeep
-    int food_cost = 0;       // Food upkeep
-    int shield_cost = 0;     // Shield upkeep
-    bool upgradable = false; // Unit type is upgradable
-
-    unit_list_iterate(client_player()->units, punit)
+    if (client_has_player() && pplayer != client_player()) {
+      continue;
+    }
```
Comment (lmoureaux) [inline client/views/view_units.cpp:538]: How is this different from doing the following?
```cpp
auto pplayer = client_player();
if (!pplayer) {
  return;
}
```

Comment (jwrober) [reply client/views/view_units.cpp:538]: I didn't know that was an option I guess. Is the code better your way?

Comment (jwrober) [reply client/views/view_units.cpp:538]: I test it with your code and it breaks the view.
