### PR TITLE
Fix Coverity issues

### LINKED ISSUE #2375: New Coverity warnings
**Describe the bug**
Coverity is unhappy about the tileset and mapgen PRs (mostly)

image

**To Reproduce**
1. Open coverity report

**Expected behavior**
Fix discovered issues

**Platform and version (please complete the following information):**
 - OS: CI
 - Freeciv21 version: master

### PR DESCRIPTION
**Pull request by blabber**
Closes #2375

### CODE REVIEW

File: ai/default/aiunit.cpp [hunk 1]
```diff
@@ -796,7 +797,9 @@ int look_for_charge(struct ai_type *ait, struct player *pplayer,
         continue;
       }
       // Reduce want based on move cost.
-      def >>= move_cost / (2 * std::min(1, unit_move_rate(punit)));
+      int divisor = (2 * std::min(1, unit_move_rate(punit)));
```
Comment (lmoureaux) [inline ai/default/aiunit.cpp:800]: This looks like a logic error, the `min` will always return 1. Should likely be a `max`.

Comment (blabber) [reply ai/default/aiunit.cpp:800]: You are probably right, but I'd rather not change existing logic, when the goal is to fix a possible division by zero reported by a static analyzer.

Comment (XHawk87) [reply ai/default/aiunit.cpp:800]: The only reason that could cause a division by zero is this error in the first place :P
