### PR TITLE
Don't change Nations button for a meeting

### LINKED ISSUE #1396: Label for "Nations" button in top bar disappears after a diplomatic meeting
**Describe the bug**
If a diplomatic meeting gets activated, the "Nations" button changes to reflect this by changing the label. This is fine, working as intended. After the meeting concludes, it doesn't return to its original state and has an empty label. That's the bug.

**To Reproduce**
1. Observe the "Nations" button in top bar has the text "Nations"
2. Activate a diplomatic meeting with another nation
3. Observe the "Nations" button in top bar changes text to the nation's name (working as intended)
4. Conclude the diplomatic meeting by either accepting or rejecting it
5. Observe the "Nations" button in top bar now has no label

**Expected behavior**
The "Nations" button should go back to its original label after all diplomatic meetings are concluded.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 4
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

### PR DESCRIPTION
**Pull request by Koffy25**
Closes #1396

### CODE REVIEW

File: client/diplodlg.cpp [hunk 1]
```diff
@@ -880,10 +879,6 @@ void handle_diplomacy_init_meeting(int counterpart, int initiated_from)
   hmid = qMax(1, hmid);
   p.drawPixmap(1, hmid, *pix2);
   p.end();
-  queen()->sw_diplo->setIcon(QIcon(*pix3));
```
Comment (lmoureaux) [inline client/diplodlg.cpp:883]: I think we can also remove anything related to `pix3` since it wasn't used anywhere else (right?). It looks like `pix` and `pix2` have also become useless.

Comment (Koffy25) [reply client/diplodlg.cpp:883]: Aren't they used for the diplomacy screen?

Comment (lmoureaux) [reply client/diplodlg.cpp:883]: At least `pix2` and `pix3` are deleted immediately after this code so I don't think they're used

**Review by lmoureaux — APPROVED** [review]
One last nitpick, I think `QPainter p;` has also become unused now

**Comment by lmoureaux** [comment]
Thanks!
