### PR TITLE
fix uwt table on units view to show all units

### LINKED ISSUE #1865: New units view UWT table does not show all units w/ UWT
**Describe the bug**
The units view page has a table of units subject to `unitwaittime`. However the table only shows one unit type item with the least amount of time remaining.

Example:
2 Muskets are subject to `unitwaittime`. One has 9 hours and 10 minutes left and another has 8 hours and 10 minutes left. The table will show the one with 8 hours and 10 minutes left only and when that timer expires the table will show the other Musket with 1 hour and 10 minutes left. 

**To Reproduce**
1. Open a game that is subject to UWT
2. Move some units of the same type to expose them to the UWT counter
3. Open the units view

**Expected behavior**
The UWT table shows every unit subject to UWT and not just one of a particular type.

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-dev
 - Ruleset/Longturn game (if applicable): LTX/LTT or any game with UWT.

**Additional context**
Problem code is here - https://github.com/longturn/freeciv21/blob/master/client/views/view_units.cpp#L611

### PR DESCRIPTION
**Pull request by jwrober**
closes #1865

### CODE REVIEW

File: client/views/view_units.cpp [hunk 1]
```diff
@@ -607,39 +608,33 @@ void get_units_waiting_data(struct unit_waiting_entry *entries,
   if (nullptr == client.conn.playing) {
     return;
   }
+  const struct unit_type *ut; // Init unit_type struct
+  int pcity_near_dist = 0;    // Init distance
+  QString city = "";          // Init city name string
+  time_t dt = 0;              // Init date time
```
Comment (lmoureaux) [inline client/views/view_units.cpp:614]: I don't think these declarations are used outside of the `{}` block below, so I suggest limiting their scope to it
```suggestion
```

File: client/views/view_units.cpp [hunk 2]
```diff
@@ -607,39 +608,33 @@ void get_units_waiting_data(struct unit_waiting_entry *entries,
...
 
-      if (unit_type_get(punit) == unittype && !can_unit_move_now(punit)
-          && punit->ssa_controller == SSA_NONE) {
-        count++;
-        city = get_nearest_city_text(pcity_near, pcity_near_dist);
-        dt = time(nullptr) - punit->action_timestamp;
-      }
+      entries[*num_entries_used].type = ut;
+      entries[*num_entries_used].city_name = city;
+      entries[*num_entries_used].timer = dt;
```
Comment (lmoureaux) [inline client/views/view_units.cpp:627]: We can set things directly here:
```suggestion
      entries[*num_entries_used].type = punit->utype;
      entries[*num_entries_used].city_name = get_nearest_city_text(pcity_near, pcity_near_dist);
      entries[*num_entries_used].timer = time(nullptr) - punit->action_timestamp;
```

File: client/views/view_units.cpp [hunk 3]
```diff
@@ -607,39 +608,33 @@ void get_units_waiting_data(struct unit_waiting_entry *entries,
...
-    time_t dt = 0;
+    struct city *pcity_near = get_nearest_city(punit, &pcity_near_dist);
 
-    unit_list_iterate(client.conn.playing->units, punit)
-    {
-      struct city *pcity_near = get_nearest_city(punit, &pcity_near_dist);
+    if (!can_unit_move_now(punit) && punit->ssa_controller == SSA_NONE) {
+      ut = punit->utype;
+      city = get_nearest_city_text(pcity_near, pcity_near_dist);
+      dt = time(nullptr) - punit->action_timestamp;
```
Comment (lmoureaux) [inline client/views/view_units.cpp:623]: Actually, remove the intermediate variables altogether?
```suggestion
```
