### PR TITLE
Fixed fix about fixing mem leak in page load

### LINKED ISSUE #349: Selecting a saved game to load crashes the client
Choose "Load saved game", select a game in the list. If it doesn't crash, select another one until the client crashes.

I've seen at least two different segfaults. Here is the first one, deleting a `QHash` that doesn't exist (`gdb` can't read at `0xc0b0`):
```
Thread 1 "freeciv-qt" received signal SIGSEGV, Segmentation fault.
0x00005555559a1cf4 in QHash<QString, entry*>::~QHash (this=0xc0b0, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qhash.h:250
250         ~QHash() { if (!d->ref.deref()) freeData(d); }
(gdb) bt
#0  0x00005555559a1cf4 in QHash<QString, entry*>::~QHash (this=0xc0b0, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qhash.h:250
#1  0x00005555559a1c84 in QMultiHash<QString, entry*>::~QMultiHash (this=0xc0b0, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qhash.h:1020
#2  0x00005555559a1503 in secfile_destroy (secfile=0x55555c8430d0) at ../utility/section_file.cpp:94
#3  0x00005555557622fb in page_load::slot_selection_changed (this=0x555556c2a280, selected=..., deselected=...) at ../client/gui-qt/page_load.cpp:349
#4  0x00005555557643de in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QItemSelection const&, QItemSelection const&>, void, void (page_load::*)(QItemSelection const&, QItemSelection const&)>::call (f=
    (void (page_load::*)(page_load * const, const QItemSelection &, const QItemSelection &)) 0x555555760da0 <page_load::slot_selection_changed(QItemSelection const&, QItemSelection const&)>, o=0x555556c2a280, arg=0x7fffffffce20) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#5  0x00005555557642c0 in QtPrivate::FunctionPointer<void (page_load::*)(QItemSelection const&, QItemSelection const&)>::call<QtPrivate::List<QItemSelection const&, QItemSelection const&>, void> (f=
    (void (page_load::*)(page_load * const, const QItemSelection &, const QItemSelection &)) 0x555555760da0 <page_load::slot_selection_changed(QItemSelection const&, QItemSelection const&)>, o=0x555556c2a280, arg=0x7fffffffce20) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#6  0x000055555576404f in QtPrivate::QSlotObject<void (page_load::*)(QItemSelection const&, QItemSelection const&), QtPrivate::List<QItemSelection const&, QItemSelection const&>, void>::impl (which=1, this_=0x555557004720, r=0x555556c2a280, a=0x7fffffffce20, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418
#7  0x00007ffff6b32d86 in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff6aa5731 in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) () from /usr/lib/libQt5Core.so.5
```

And the second one, probably sending a signal to a deleted object:
```
Thread 1 "freeciv-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff7040f1e in QTextCursor::charFormat() const () from /usr/lib/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff7040f1e in QTextCursor::charFormat() const () from /usr/lib/libQt5Gui.so.5
#1  0x00007ffff77af8d4 in ?? () from /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff77bc85c in ?? () from /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff6b32dc0 in ?? () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff700b6ee in QTextDocumentPrivate::finishEdit() () from /usr/lib/libQt5Gui.so.5
#5  0x00007ffff6ff9b26 in QTextDocument::setHtml(QString const&) () from /usr/lib/libQt5Gui.so.5
#6  0x00007ffff76fe021 in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff76feb8d in ?? () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff7700466 in ?? () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff7700bf9 in QLabel::minimumSizeHint() const () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff7700cc6 in QLabel::sizeHint() const () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff75e88f2 in QWidgetItemV2::updateCacheIfNecessary() const () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff75e8cd6 in QWidgetItemV2::maximumSize() const () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff75dc7fa in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff75dd888 in non-virtual thunk to QBoxLayout::maximumSize() const () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff75dc7fa in ?? () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff75ddea8 in QBoxLayout::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff75e4068 in QLayoutPrivate::doResize() () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff75e55de in QLayout::activate() () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff75c5735 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff6afba2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#21 0x00007ffff6afe523 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
```

### PR DESCRIPTION
**Pull request by mir3x**
Fixed #349

### CODE REVIEW

File: client/gui-qt/page_load.cpp [hunk 1]
```diff
@@ -313,7 +313,7 @@ void page_load::slot_selection_changed(const QItemSelection &selected,
           if (pterr != NULL) {
             const char *iptr = secfile_lookup_str_default(
                 sf, NULL, "savefile.terrident%d.identifier", ii);
-            if (iptr != nullptr) {
+            if (!iptr) {
               secfile_destroy(sf);
               fc_assert_ret(iptr != nullptr);
```
Comment (lmoureaux) [inline client/gui-qt/page_load.cpp:318]: Should be `fc_assert_ret(!iptr);`

**Review by lmoureaux — CHANGES_REQUESTED** [review]
Nice finding!

File: client/gui-qt/page_load.cpp (hunk 1 above)
Comment (mir3x) [reply client/gui-qt/page_load.cpp]: fixed

**Review by lmoureaux — APPROVED** [review]
