### PR TITLE
Change the name of the local and server options dialog boxes

### LINKED ISSUE #1368: Game menu -> Set Local Options should be changed
**Describe the bug**
Game -> Set local options menu is not well named. Same with Game -> Server Options. 

**Expected behavior**
Change local options to "interface options" or "gui options".
Change server options to "game options", since the server runs the game.

**Add any other context about the problem here.**
Came up as part of thinking about the documentation meta issue

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1368 

Also fixed a few capitalization on the other menu entries on the Game menu.

### CODE REVIEW

File: client/menu.cpp [hunk 1]
```diff
@@ -563,17 +563,17 @@ void mr_menu::setup_menus()
...
   connect(act, &QAction::triggered, this, &mr_menu::local_options);
-  act = menu->addAction(_("Server Options"));
+  act = menu->addAction(_("Game Options"));
   connect(act, &QAction::triggered, this, &mr_menu::server_options);
   act = menu->addAction(_("Messages"));
   connect(act, &QAction::triggered, this, &mr_menu::messages_options);
   act = menu->addAction(_("Shortcuts"));
   connect(act, &QAction::triggered, this, &mr_menu::shortcut_options);
-  act = menu->addAction(_("Load another tileset"));
+  act = menu->addAction(_("Load Another tileset"));
```
Comment (lmoureaux) [inline client/menu.cpp:574]: `tileset` should be capitalized here

**Comment by jwrober** [comment]
I need to update the client manual with this change before it can be merged.

**Review by lmoureaux — APPROVED** [review]
Finally we got rid of `Set client options` :tada: I've wanted to fill an issue about this for *ages*
