### PR TITLE
Fix help to better state cultivate and transform

### LINKED ISSUE #721: Terrain help doesn't distinguish between Cultivate and Irrigate
**Describe the bug**

The two are now separate, but the help keeps merging them.

**To Reproduce**
1. Go to Help > Terrain > Swamp
2. Look at the help for Irrig. Reslt
3. Swamp can't be irrigated, only cultivated

**Expected behavior**

It shows "Cultivate result" or something similar.

**Screenshots**

image

**Platform and version (please complete the following information):**
 - OS: ?, probably any
 - Freeciv21 version: 3.0-alpha9
 - Ruleset/Longturn game (if applicable): `classic` or `Sim30`

**Additional context**

https://github.com/longturn/freeciv21/blob/79e53d66ab39f06f26c8ae78193aa110da3fd46d/client/gui-qt/helpdlg.cpp#L1355-L1364

### PR DESCRIPTION
**Pull request by jwrober**
Closes #721

### CODE REVIEW

File: client/gui-qt/helpdlg.cpp [hunk 1]
```diff
@@ -1359,7 +1359,7 @@ void help_widget::set_topic_terrain(const help_item *topic,
       fc_snprintf(buffer, sizeof(buffer),
                   PL_("%d turn", "%d turns", pterrain->cultivate_time),
                   pterrain->cultivate_time);
-      str = N_("Irrig. Rslt/Time:");
+      str = N_("Cultivate Rslt/Time:");
```
Comment (lmoureaux) [inline client/gui-qt/helpdlg.cpp:1362]: Does checking the `irrigation_result` in the `if` still make sense?

Comment (jwrober) [reply client/gui-qt/helpdlg.cpp:1362]: Based on my limited experience with the code I think so. I was mostly after changing the string value to fix the bug and get rid of "Trans." to a fully spelled out "Transform".

Comment (lmoureaux) [reply client/gui-qt/helpdlg.cpp:1362]: Convinced by the multiple tests shown privately.
